"""adicionando campo de foto a usuarios

Revision ID: 6cd0c9f39c78
Revises: 88c3864f97aa
Create Date: 2026-10-01 12:11:21.106275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd0c9f39c78'
down_revision = '88c3864f97aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
